---
downloads: ~/.ansible-downloads/

# we use a dummy file as we manage NVM init via dotfiles
nvm_shell_init_file: ~/.nvm_profile

configure_dotfiles: true

git_user_name: Jamie Shiell
git_user_email: jamie@infernus.org
git_user_signingkey: 1C25BF0EE37BF38E

dotfiles_files:
  - { src: curlrc, dest: .curlrc }
  - { src: vim/vimrc, dest: .vimrc }
  - { src: zsh/zshrc, dest: .zshrc }
  - { src: vim, dest: .vim }
  - { src: alacritty, dest: .config/alacritty }
  - { src: ghostty, dest: .config/ghostty }
  - { src: zed, dest: .config/zed }
  - { src: starship.toml, dest: .config/starship.toml }

homebrew_taps:
  - cloudfoundry/tap
  - bell-sw/liberica

homebrew_installed_packages:
  - bat
  - docker
  - docker-compose
  - fd
  - git
  - git-delta
  - gnupg
  - httpie
  - iftop
  - jenv
  - jq
  - mas
  - mise
  - mtr
  - noti
  - pinentry-mac
  - pipx
  - prettyping
  - python
  - tldr
  - tmux

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: true
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - arq
  - autodesk-fusion
  - banktivity
  - bartender
  - battle-net
  - betterdisplay
  - calibre
  - daisydisk
  - discord
  - doxie
  - fantastical
  - firefox
  - font-monaspace-nerd-font
  - ghostty
  - google-chrome
  - google-cloud-sdk
  - intellij-idea-ce
  - keepingyouawake
  - little-snitch
  - moom
  - mullvadvpn
  - omnigraffle
  - orbstack
  - prusaslicer
  - scroll-reverser
  - signal
  - steam
  - slack
  - liberica-jdk17
  - liberica-jdk21
  - transmit
  - visual-studio-code
  - vivaldi
  - zed
