---
downloads: ~/.ansible-downloads/

# we use a dummy file as we manage NVM init via dotfiles
nvm_shell_init_file: ~/.nvm_profile

configure_dotfiles: true

git_user_name: Jamie Shiell
git_user_email: jamie@infernus.org
git_user_signingkey: 1C25BF0EE37BF38E

dotfiles_files:
  - { src: curlrc, dest: .curlrc }
  - { src: vim/vimrc, dest: .vimrc }
  - { src: zsh/zshrc, dest: .zshrc }
  - { src: vim, dest: .vim }

homebrew_taps:
  - cloudfoundry/tap
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - bell-sw/liberica

homebrew_installed_packages:
  - bat
  - docker
  - docker-compose
  - fd
  - git
  - git-delta
  - gnupg
  - httpie
  - iftop
  - jenv
  - jq
  - mas
  - mtr
  - noti
  - pinentry-mac
  - prettyping
  - python
  - rbenv
  - rbenv-bundler
  - rbenv-bundler-ruby-version
  - ruby-build
  - the_silver_searcher
  - tldr
  - tmux

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: true
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - banktivity
  - bartender
  - battle-net
  - calibre
  - daisydisk
  - discord
  - doxie
  - fantastical
  - firefox
  - font-monaspace
  - google-chrome
  - google-cloud-sdk
  - intellij-idea
  - iterm2
  - little-snitch
  - moom
  - omnigraffle
  - scroll-reverser
  - signal
  - steam
  - slack
  - liberica-jdk17
  - liberica-jdk21
  - transmit
  - visual-studio-code
