---
# All credit to https://github.com/geerlingguy/ansible-role-dotfiles/

- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo | default('git@github.com:jshiell/dotfiles') }}"
    dest: "{{ dotfiles_repo_local_destination | default('~/dotfiles') }}"
    version: "{{ dotfiles_repo_version | default('main') }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey | default(false) }}"
    recursive: true
  become: false

- name: Ensure all configured dotfiles are links.
  command: "ls -F {{ dotfiles_home | default('~') }}/{{ item }}"
  register: existing_dotfiles_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Remove existing dotfiles file if a replacement is being linked.
  file:
    path: "{{ dotfiles_home | default('~') }}/{{ dotfiles_files[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfiles_info.results }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination | default('~/dotfiles') }}/{{ item }}"
    dest: "{{ dotfiles_home | default('~') }}/.{{ item }}"
    state: link
    mode: 0644
  become: false
  with_items: "{{ dotfiles_files }}"
