---
# All credit to https://github.com/geerlingguy/ansible-role-dotfiles/

- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo | default('git@github.com:jshiell/dotfiles') }}"
    dest: "{{ dotfiles_repo_local_destination | default('~/dotfiles') }}"
    version: "{{ dotfiles_repo_version | default('main') }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey | default(false) }}"
    recursive: true
  become: false

- name: Ensure all configured dotfiles are links.
  command: "ls -F {{ dotfiles_home | default('~') }}/{{ item.dest }}"
  register: existing_dotfiles_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination | default('~/dotfiles') }}/{{ item.src }}"
    dest: "{{ dotfiles_home | default('~') }}/{{ item.dest }}"
    state: link
  become: false
  with_items: "{{ dotfiles_files }}"
  become: false
