---
- name: Ensure git is installed
  homebrew:
    name: git
    state: present

- name: Configure Git
  shell: |
    git config --global user.name '{{ git_user_name }}'
    git config --global user.email '{{ git_user_email }}'

    git config --global user.signingkey '{{ git_user_signingkey }}'
    git config --global commit.gpgsign {{ git_commit_gpgsign | default(true) }}

    git config --global pull.rebase true
    git config --global init.defaultBranch main
    git config --global log.follow true
    git config --global core.commentChar ";"
    git config --global --add --bool push.autoSetupRemote true

    git config --global core.pager "delta"
    git config --global interactive.diffFilter "delta --color-only"
    git config --global diff.colorMoved default
    git config --global mergetool.conflictstyle diff3
    git config --global delta.navigate true
    git config --global delta.side-by-side true
  become: false
