- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: powerline
  register: tempdir

- name: Download Powerline fonts
  git:
    repo: "https://github.com/powerline/fonts"
    dest: "{{ tempdir.path }}"
  tags:
    - powerline-fonts

- name: Install Powerline fonts
  shell: |
    cd "{{ tempdir.path }}"
    ./install.sh
  become: false
