---
- name: Check if {{ nvm_node_version }} is the default Node.js version
  shell: >
    set -o pipefail && \
    . ./nvm.sh && \
    nvm alias default --no-colors | grep '{{ nvm_node_version }}'
  args:
    executable: /bin/bash
    chdir: "{{ nvm_install_path }}"
  register: nvm_check_default
  changed_when: False
  failed_when: False

- name: Set default Node.js version to {{ nvm_node_version }}
  shell: ". ./nvm.sh && nvm alias default {{ nvm_node_version }}"
  args:
    chdir: "{{ nvm_install_path }}"
  when: nvm_check_default.rc != 0
